In [11]:
import numpy as np

## Arrays

In [2]:
a = np.array([1, 4, 5, 8], float)

In [4]:
print(a, type(a))

[1. 4. 5. 8.] <class 'numpy.ndarray'>


In [12]:
a[:2]

array([1., 4.])

In [13]:
a[3]

8.0

In [14]:
a[0]=5.

In [15]:
a

array([5., 4., 5., 8.])

In [16]:
a = np.array([[1, 2, 3], [4, 5, 6]], float)

In [17]:
a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [22]:
a[0,2]

3.0

In [23]:
a[1,:]

array([4., 5., 6.])

In [24]:
a[-1,-2]

5.0

In [25]:
a.shape

(2, 3)

In [26]:
a.dtype

dtype('float64')

In [27]:
len(a)

2

In [28]:
2 in a

True

In [29]:
0 in a

False

In [33]:
b = a.reshape((3,2))

In [34]:
b

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [35]:
c = a.copy()
a[0,0] = 4

In [36]:
a

array([[4., 2., 3.],
       [4., 5., 6.]])

In [37]:
c

array([[1., 2., 3.],
       [4., 5., 6.]])

In [38]:
b

array([[4., 2.],
       [3., 4.],
       [5., 6.]])

In [39]:
a.tolist()

[[4.0, 2.0, 3.0], [4.0, 5.0, 6.0]]

In [40]:
list(a)

[array([4., 2., 3.]), array([4., 5., 6.])]

In [44]:
bin = a.tostring()
bin

b'\x00\x00\x00\x00\x00\x00\x10@\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x08@\x00\x00\x00\x00\x00\x00\x10@\x00\x00\x00\x00\x00\x00\x14@\x00\x00\x00\x00\x00\x00\x18@'

In [45]:
np.fromstring(bin)

/Users/tobias/miniconda3/envs/ml/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  """Entry point for launching an IPython kernel.


array([4., 2., 3., 4., 5., 6.])

In [47]:
b.fill(0)
b

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [59]:
a = np.array(range(6), float)
a

array([0., 1., 2., 3., 4., 5.])

In [67]:
a = a.reshape((2, 3))
a

array([[0., 1., 2.],
       [3., 4., 5.]])

In [65]:
b = a.transpose()
b

array([[0., 3.],
       [1., 4.],
       [2., 5.]])

In [68]:
a.flatten()

array([0., 1., 2., 3., 4., 5.])

In [71]:
np.concatenate((a,b.reshape((2,3))))

array([[0., 1., 2.],
       [3., 4., 5.],
       [0., 3., 1.],
       [4., 2., 5.]])

In [75]:
np.concatenate((a,b.reshape((2,3))), axis=1)

array([[0., 1., 2., 0., 3., 1.],
       [3., 4., 5., 4., 2., 5.]])

In [76]:
a

array([[0., 1., 2.],
       [3., 4., 5.]])

In [92]:
b = a[:,np.newaxis]
b.shape

(2, 1, 3)

In [93]:
b

array([[[0., 1., 2.]],

       [[3., 4., 5.]]])

## other ways, create arrays

In [95]:
np.arange(5, dtype=float)

array([0., 1., 2., 3., 4.])

In [96]:
np.arange(1, 6, 2, dtype=int)

array([1, 3, 5])

In [97]:
np.ones((2,3), dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [98]:
np.zeros(7, dtype=int)

array([0, 0, 0, 0, 0, 0, 0])

In [99]:
np.zeros_like(a)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [100]:
np.ones_like(a)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [101]:
np.identity(4, dtype=float)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [102]:
np.eye(4, k=1, dtype=float)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

## mathematics

In [103]:
a = np.array([1,2,3], float)
b = np.array([5,2,6], float)

In [104]:
a+b

array([6., 4., 9.])

In [105]:
a-b

array([-4.,  0., -3.])

In [106]:
a*b

array([ 5.,  4., 18.])

In [107]:
a/b

array([0.2, 1. , 0.5])

In [110]:
a%b

array([1., 0., 3.])

In [111]:
a**b

array([  1.,   4., 729.])

In [112]:
a = np.array([[1,2], [3,4]], float)
b = np.array([[2,0], [1,3]], float)
a * b

array([[ 2.,  0.],
       [ 3., 12.]])

In [113]:
a = np.array([1.1, 1.5, 1.9], float)
np.rint(a)

array([1., 2., 2.])

## interations

In [122]:
for x in a:
    print(x)

1.1
1.5
1.9


In [123]:
a = np.array([[1, 2], [3, 4], [5, 6]], float)
for x in a:
    print(x)

[1. 2.]
[3. 4.]
[5. 6.]


In [124]:
for (x,y) in a:
    print(x,y)

1.0 2.0
3.0 4.0
5.0 6.0


## operations

In [125]:
a.sum()

21.0

In [127]:
np.prod(a)

720.0

In [128]:
a.mean()

3.5

In [129]:
np.var(a)

2.9166666666666665

In [130]:
a.std()

1.707825127659933

In [132]:
a.min()

1.0

In [134]:
a.argmin() # index

0

In [135]:
a.mean(axis=0)

array([3., 4.])

In [136]:
a.min(axis=1)

array([1., 3., 5.])

In [140]:
a.clip(2,4)

array([[2., 2.],
       [3., 4.],
       [4., 4.]])

In [141]:
np.unique(a)

array([1., 2., 3., 4., 5., 6.])

In [142]:
a.diagonal()

array([1., 4.])

## comparison

In [145]:
b = b.reshape(3,2)
a > b

array([[False,  True],
       [ True,  True],
       [ True,  True]])

In [146]:
a <= b

array([[ True, False],
       [False, False],
       [False, False]])

In [147]:
a > 5

array([[False, False],
       [False, False],
       [False,  True]])

In [158]:
c = (a > b).flatten()
any(c)

True

In [159]:
all(c)

False

In [160]:
np.logical_and(a > 0, a < 3)

array([[ True,  True],
       [False, False],
       [False, False]])

In [161]:
np.logical_or(a > 4, a < 2)

array([[ True, False],
       [False, False],
       [ True,  True]])

In [163]:
np.logical_not(a == 4)

array([[ True,  True],
       [ True, False],
       [ True,  True]])

In [165]:
np.where(a > 3, 'it\'s true', 'it\'s false') # bool, if true if false

array([["it's false", "it's false"],
       ["it's false", "it's true"],
       ["it's true", "it's true"]], dtype='<U10')

In [169]:
a.nonzero()

(array([0, 0, 1, 1, 2, 2]), array([0, 1, 0, 1, 0, 1]))

In [171]:
a = np.array([1, np.NaN, np.Inf], float)
a

array([ 1., nan, inf])

In [172]:
np.isnan(a)

array([False,  True, False])

In [174]:
np.isfinite(a)

array([ True, False, False])

## item selection / manipulation

In [175]:
a = np.array([[6, 4], [5, 9]], float)
a >= 6

array([[ True, False],
       [False,  True]])

In [176]:
a[a >= 6]

array([6., 9.])

In [183]:
a[np.logical_and(a > 5, a < 9)]

array([6.])

In [209]:
a = np.array([1, 2, 3, 4], float)
b = np.array([0, 0, 1, 3, 2, 1], int)
a[b]

array([1., 1., 2., 4., 3., 2.])

In [210]:
a = np.array([[1, 4], [9, 16]], float)
b = np.array([0, 0, 1, 1, 0], int)
c = np.array([0, 1, 1, 1, 1], int)
a[b,c]

array([ 1.,  4., 16., 16.,  4.])

In [212]:
a = np.array([1, 2, 3, 4], float)
b = np.array([0, 0, 1, 3, 2, 1], int)
a.take(b)

array([1., 1., 2., 4., 3., 2.])

In [217]:
a = np.array([0, 1, 2, 3, 4, 5], float)
b = np.array([9, 8, 7], float)
a.put([0, 1, 3], b)
a

array([9., 8., 2., 7., 4., 5.])

## vector and matrices

In [220]:
a = np.array([1, 2, 3], float)
b = np.array([0, 1, 1], float)
np.dot(a, b)

5.0

In [223]:
a = np.array([[4, 2, 0], [9, 3, 7], [1, 2, 1]], float)
det = np.linalg.det(a) # determinant
vals, vecs = np.linalg.eig(a) # eigenvalues, eigenvectors
print(det, vals, vecs)

-48.00000000000003 [ 8.85591316  1.9391628  -2.79507597] [[-0.3663565  -0.54736745  0.25928158]
 [-0.88949768  0.5640176  -0.88091903]
 [-0.27308752  0.61828231  0.39592263]]


In [224]:
np.linalg.inv(a) # inverse

array([[ 0.22916667,  0.04166667, -0.29166667],
       [ 0.04166667, -0.08333333,  0.58333333],
       [-0.3125    ,  0.125     ,  0.125     ]])

In [226]:
U, s, Vh = np.linalg.svd(a) # singular value decomposition
print(U, s, Vh)

[[-0.29985681  0.92246475 -0.24319679]
 [-0.94145661 -0.32731996 -0.0807533 ]
 [-0.15409523  0.2047448   0.96660966]] [12.48911658  2.62158178  1.46604097] [[-0.78681562 -0.29884211 -0.5400135 ]
 [ 0.36188998  0.48537842 -0.79589159]
 [-0.49995682  0.82164541  0.27375536]]


## polynomial mathematics

In [227]:
np.poly([-1, 1, 1, 10]) # 𝑥4 − 11𝑥3 + 9𝑥2 + 11𝑥 − 10

array([  1., -11.,   9.,  11., -10.])

In [228]:
np.roots([1, 4, -2, 3]) # find coefficient roots

array([-4.5797401 +0.j        ,  0.28987005+0.75566815j,
        0.28987005-0.75566815j])

In [229]:
np.polyint([1, 1, 1, 1]) # integrate

array([0.25      , 0.33333333, 0.5       , 1.        , 0.        ])

In [230]:
np.polyder([1./4., 1./3., 1./2., 1., 0.]) # derivate

array([1., 1., 1., 1.])

In [231]:
np.polyval([1, -2, 0, 2], 4) # 𝑥3 − 2𝑥2 + 2 at x = 4

34

In [232]:
x = [1, 2, 3, 4, 5, 6, 7, 8]
y = [0, 2, 1, 3, 7, 10, 11, 19]
np.polyfit(x, y, 2) # fit poly to values

array([ 0.375     , -0.88690476,  1.05357143])

## statistics

In [233]:
a = np.array([1, 4, 3, 8, 9, 2, 3], float)
np.median(a)

3.0

In [235]:
a = np.array([[1, 2, 1, 3], [5, 3, 1, 8]], float)
np.corrcoef(a) # correlation coefficient

array([[1.        , 0.72870505],
       [0.72870505, 1.        ]])

In [236]:
np.cov(a) # covariance

array([[0.91666667, 2.08333333],
       [2.08333333, 8.91666667]])

## random

In [238]:
np.random.seed(1)
np.random.rand(5)

array([4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01,
       1.46755891e-01])

In [239]:
np.random.rand(2,3)

array([[0.09233859, 0.18626021, 0.34556073],
       [0.39676747, 0.53881673, 0.41919451]])

In [240]:
np.random.random()

0.6852195003967595

In [241]:
np.random.poisson(6.0) # poisson lamda = 6

4

In [242]:
np.random.normal(1.5, 4.0) # gaussian mean = 1.5, std = 4

-2.941452218945237

In [243]:
np.random.normal() # mu = 0, sigma = 1

0.18121426663539714

In [244]:
np.random.normal(size=5)

array([ 0.56434487, -0.56651023,  0.7299756 ,  0.37299379,  0.53381091])

In [248]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [274]:
a = [x for x in range(10)]
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [277]:
b = np.random.shuffle(a)
b